Repository Kinoxyz/weather, pull requests merged in 2023-11, with the labels that each got.

#48 Added basic settings option
  .prettierrc
  public/settings_material.svg
  src/App.svelte
  src/components/Modal.svelte
  src/components/SettingsButton.svelte
  src/components/WeatherCard.svelte
  src/components/widgets/CurrentWeatherConditionWidget.svelte
  src/components/widgets/DailyWeatherConditionWidget.svelte
  src/models/Temperature.ts
  src/stores.ts
Labels: enhancement, frontend

#54 Add direnv integration
  .envrc
  .gitignore
  flake.nix
Labels: dependencies

#56 Add back macOS to the publish action
  .github/workflows/publish.yml
Labels: enhancement, CI

#55 Update metadata
  README.md
  package.json
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/tauri.conf.json
Labels: enhancement
